{
	"data": "ENC[AES256_GCM,data:1lGlANgonNJR7+3vBrXwMIci7aj4VHtuY7eYs+608rPLtvTECIZFJjD79w1CBFz971IkEf+kflo2NoTCmMAmSDDLAfunkSfy75mTxPcXobO+x96EmO3iYzQijyjndpBlMZVmAbMDPZHFPkbTGCTbPxoWRrrkHcaaF6RU0ujvnOTI3P7zzSOk7/HQGdsWqXajAXd+b9JZCVqnexsDdbAZrb2q57Prw2LFvpp/6OVFWTmyz6Q74wyJcHA5DQmsSTwoiFforZLOgJ517lU6d2JzlECm4wQMwri06TxnWrbY82jDJmpcNehbT7xSndbwLaIxCPMtcjVUp5YVx640FWvr1NG/OQ==,iv:c+lZltuC3rUJ7+I32P1/XsihxAFVOfraeq3YZlftjtI=,tag:0HdWKMLXcF6mR6YQEYE0Ug==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": [
			{
				"recipient": "age1vqpwj9z3qaw625akwfjcukpdscywzm6ncm7v56ndgh9dmxvwqpmq0ccxca",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnWDlRVENZTkRYWmFZdTRX\nKzdyYk41bnNKTW90QkRPejl3bXZSRWVNWVc4CmxkTndDcFZ4Ky83MExxVUVLVzVp\nZ2E4amsxcktzZi84RUh3clRObnVFeDgKLS0tIHlPcm5CZ3ZlakYyaXZqcmptZlIr\nNnJPYWxRK0IvZHB6c1cwTEpHSWNCdWMKP2MLYTvmEhpR07ZUktePPozaU0yLKaub\nM8nCM0F/kcYe5aIk5npkDoTrUTMZ/vYbOUv9ohcR4F6APHZ1PjqusQ==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2025-04-17T07:38:45Z",
		"mac": "ENC[AES256_GCM,data:g05+N09Ud7amnuKuBz2eeos+Uo2KAD5P9FJxobwsj50FoSwZk+a+pgwgaUWPau3CIAqQoJ6G7PNfnziYOLsrmiIFiXZJszpNQZGtdTVQpkbcT7xm0UAiwtboRIjEr/ojiD4+Yz6vazP1/tEM7sHauYEugka3f1n1DvibMIKXF5I=,iv:Mssrtofv07DWkvHkcEXx1Xk9WfZIO0Z5QxY+bw11v94=,tag:xctML5rhMoCA6aYkxZmuaA==,type:str]",
		"pgp": null,
		"unencrypted_suffix": "_unencrypted",
		"version": "3.9.4"
	}
}